### ISSUE TITLE
Update the library to work with nightly Nargo

### ISSUE THREAD

**Issue by LogvinovLeon** [aragonzkresearch/noir-trie-proofs#14]
Lately nargo introduces a breaking change that you can't do binary arithmetic operations it the type of operands is not the same.
When I try to compile this library on nightly - I get more than a 100 errors, because most of the values are fields, but loop indexes are u64.

This issue is to bring this library up to date with nightly nargo.

I understand that usually it's not a great idea to jump on experimental releases as some things can change, but with nargo bug fixes are not backported, so experimental is probably what will be in 0.25.0 and those changes see, like they're there to stay. Optionaly - consult nargo team on it

**Comment by ax0** [comment]
Thanks for the heads-up! I've made the necessary changes. This should be fixed with c00debf.
